### PR TITLE
fix(runtime): tighten desktop local path boundaries

### LINKED ISSUE #339: 优化：Workspace 与本地路径改造方案
# 打包版工作区路径改造说明

## 问题描述

- 当前 `workspace` 不是“用户机器上的真实默认目录”，而是**后端默认的相对占位值**。

### 当前来源

- 后端默认设置工作区为 `"workspace"`  
  - 相关代码：`services/local-service/internal/runengine/engine.go:19`
- 桌面端遇到相对路径时，会解析为“仓库根目录 + workspace”  
  - 相关代码：`apps/desktop/src-tauri/src/main.rs:355`、`apps/desktop/src-tauri/src/main.rs:362`
- 控制面板里的路径校验也按这个 repo root 拼相对路径  
  - 相关代码：`apps/desktop/src-tauri/src/control_panel_path.rs:105`

### 打包分发的问题

- `repo root` 来源于 `env!("CARGO_MANIFEST_DIR")`，它是**编译机器上的源码路径**，不是用户安装路径  
  - 相关代码：`apps/desktop/src-tauri/src/main.rs:355`
- 开发时等价于 `<你的仓库>/workspace`  
- 打包给别人后，这个默认值不适合作为正式默认路径
- 用户机器上如果没手动改成绝对路径，默认 `workspace` 的校验/打开大概率会失败

## 建议

- 给别人使用时，不要再默认 repo-relative `workspace`  
- 更合理的是改成**运行时目录**，二选一：
  1. `AppLocalData/CialloClaw/workspace`（推荐，应用自管）
  2. `Documents/CialloClaw`（用户可直接看到，更直观）

---

> 如果同意，可以做一个“打包版工作区路径改造方案”，把前后端如何统一、如何迁移旧值讲清楚。

# Workspace 与本地路径改造方案

## 现状

- **后端文件根目录**  
  - 来源：`cfg.WorkspaceRoot`  
  - 默认值："workspace"，启动时按进程当前目录转成绝对路径  
  - 相关代码：  
    - `services/local-service/internal/config/config.go:42`  
    - `services/local-service/internal/platform/adapters.go:70`

- **前端 / 宿主打开本地路径**  
  - 将相对 `workspace` 按 `CARGO_MANIFEST_DIR` 映射回仓库根  
  - 仅适合开发环境  
  - 相关代码：`apps/desktop/src-tauri/src/main.rs:355`

- **用户设置**  
  - `general.download.workspace_path` 默认值："workspace"  
  - 并不真正驱动执行根目录；执行根目录在 bootstrap 阶段固定  
  - 相关代码：  
    - `services/local-service/internal/runengine/engine.go:19`  
    - `services/local-service/internal/bootstrap/bootstrap.go:66`

- **治理层依赖设置值判断 workspace 内外**  
  - 若改为绝对路径，现有判断会失真  
  - 相关代码：  
    - `services/local-service/internal/orchestrator/service.go:4575`  
    - `services/local-service/internal/orchestrator/service.go:5664`

## 改造建议

1. **真实落盘根目录**  
   - 改为运行时绝对路径，由桌面端在启动时解析  
   - 不再依赖 repo root / cwd

2. **协议对象语义**  
   - 保持不变：`artifact` / `delivery` / `audit` / `recovery_point` 等继续使用 `workspace/...` 形式的稳定相对路径  
   - 相关代码：`services/local-service/internal/delivery/service.go:325`

3. **用户可见设置**  
   - `general.download.workspace_path` 改为真实绝对目录  
   - 用于控制面板展示和用户修改

4. **后端治理 / 审计**  
   - `out_of_workspace` 判断不再用设置字符串前缀  
   - 基于正式对象命名空间 `workspace/...` 或运行时 `cfg.WorkspaceRoot` 判断

5. **workspace_path 变更处理**  
   - 按 `restart_required` 处理  
   - 因当前文件系统根在 bootstrap 阶段构造，热切换风险较大  
   - 相关代码：`services/local-service/internal/bootstrap/bootstrap.go:66`

6. **DatabasePath 同步迁移**  
   - 例如：`DatabasePath: "data/cialloclaw.db"`  
   - 迁到运行时目录，否则打包后数据库路径不正确  
   - 相关代码：`services/local-service/internal/config/config.go:43`

## 实现顺序

1. **桌面端**  
   - 新增“运行时默认目录解析器”  
   - 提供绝对 `WorkspaceRoot` 和 `DatabasePath` 给 local-service

2. **local-service 启动参数 / 环境变量**  
   - 覆盖 `config.Load()` 中的相对默认值

3. **控制面板首屏迁移旧值**  
   - 历史值为 `"workspace"` → 映射到新默认绝对目录  
   - 已有绝对自定义路径 → 保留不变

4. **宿主打开 / 定位目录逻辑**  
   - 改为按运行时 `workspace root` 解析  
   - 不再使用 `CARGO_MANIFEST_DIR`  
   - 相关代码：`apps/desktop/src-tauri/src/main.rs:362`

5. **回写测试与文档**  
   - `trust_summary.workspace_path` 改为展示真实目录  
   - 正式对象路径仍保持 `workspace/...` 形式

### PR DESCRIPTION
**Pull request by jinyu918**
## Summary

- remove desktop host fallback to the build-time repo root and align local path handling with runtime-managed directories
- restrict desktop open/reveal actions to `workspace/...` and the trusted runtime `temp/...` scope, while keeping source-note runtime path compatibility
- make dashboard workspace display and `out_of_workspace` evaluation use the currently active runtime workspace instead of pending settings values

## Why

Packaged desktop builds should not depend on repository-relative paths or allow local-path resolution to drift with stale settings snapshots. This change closes the remaining runtime path gaps from the packaged-workspace fix and narrows the host-side open/reveal surface to the minimum trusted scope.

## Validation

- `cargo test`
- `cargo check`
- `go test ./services/local-service/internal/execution ./services/local-service/internal/orchestrator`
- `pnpm --dir apps/desktop typecheck`
- `pnpm --dir apps/desktop lint` (existing warnings only, no new errors)

## Notes

- desktop local open/reveal now accepts only `workspace/...` and `temp/...`
- source-note path resolution still supports runtime-root-relative sources for compatibility
- dashboard trust summary and impact-scope checks now reflect the runtime workspace currently bound by bootstrap, not a restart-pending settings draft

Fixes #339

### CODE REVIEW

**Comment by jinyu918** [comment]
@xgopilot 看看还有什么问题

**Comment by jinyu918** [comment]
@xgopilot 现在还有什么问题

**Comment by jinyu918** [comment]
@xgopilot 看看还有什么问题

**Comment by jinyu918** [comment]
@xgopilot 看看还有没有问题

**Comment by jinyu918** [comment]
@xgopilot 现在还有问题吗

**Comment by jinyu918** [comment]
> ### Review
> * P1 [apps/desktop/src-tauri/src/source_notes.rs#L291](/workspace/apps/desktop/src-tauri/src/source_notes.rs#L291): `resolve_source_root()` still has a path-escape hole for non-existent source roots. When `task_sources` contains something like `workspace/../../outside` (or `workspace/../data/notes`), `resolved.canonicalize()` falls back to the raw joined path because the directory does not exist yet, and the subsequent `starts_with(workspace_root)` check is only lexical. That means the path is accepted as “in workspace” even though it escapes the workspace/runtime root once created. `create_source_note()` then materializes that escaped directory with `fs::create_dir_all(target_root)` and writes the markdown file there ([source_notes.rs#L118](/workspace/apps/desktop/src-tauri/src/source_notes.rs#L118)). Since `task_sources` is user-editable through inspector settings, this still leaves a host-side write bridge outside the trusted workspace/runtime scope. The workspace-relative branch needs an explicit post-join normalization/relativize check that rejects any `..` escape before the path is trusted.
> 
> ### Verification
> * `go test ./services/local-service/internal/bootstrap ./services/local-service/internal/config ./services/local-service/internal/orchestrator ./services/local-service/internal/runengine ./services/local-service/internal/execution` passed.
> * `pnpm` is not installed in this runner, so I could not run the desktop-side JS tests here.
> 
> [View job run](https://fenno.ai/console/log/e6ff8b90-449e-4180-81bc-bf7d760608bb?at=codex)

@xgopilot 帮我修复这个问题，并重新继续review

**Comment by jinyu918** [comment]
@xgopilot 除了这个问题还有别的问题吗？请一并列出来

File: apps/desktop/src/services/settingsService.ts [hunk 1]
```diff
@@ -1,10 +1,17 @@
...
+  type DesktopRuntimeDefaults,
+} from "../platform/desktopRuntimeDefaults";
 import { syncDesktopSettingsSnapshot } from "../platform/desktopSettingsSnapshot";
 import { loadStoredValue, saveStoredValue } from "../platform/storage";
 
 // SETTINGS_KEY is the single storage key for the desktop snapshot.
 const SETTINGS_KEY = "cialloclaw.settings";
+const RUNTIME_DEFAULTS_KEY = "cialloclaw.runtime-defaults";
+const LEGACY_DEFAULT_WORKSPACE_PATH = "D:/CialloClawWorkspace";
+const LEGACY_DEFAULT_TASK_SOURCES = ["D:/workspace/todos"];
```
Comment (MeteorsLiu) [inline apps/desktop/src/services/settingsService.ts:19]: hardcode是预期的嘛

Comment (jinyu918) [reply apps/desktop/src/services/settingsService.ts:19]: 这个 hardcode 作为“历史兼容识别值”是必要的，但没必要继续承担“当前默认展示值”的角色，已经把它的职责收缩到 migration-only，这是相关 commit：https://github.com/1024XEngineer/CialloClaw/pull/370/commits/be94a45be77a576b768e57c7cba02e65b991c3d4

**Review by MeteorsLiu — APPROVED** [review]
