### PR TITLE
fix(orchestrator): unify task inspector settings and fail loud on bad sources

### LINKED ISSUE #345: bug：后端设置相关，settings真源、热更新边界与运行时绑定不一致，导致巡检/工作区/模型等配置行为分裂
### 问题概述

当前 `local-service` 对设置项的处理不是单一真源，也没有统一、清晰的热更新语义。

从代码看，至少存在下面几层并行配置来源：

1. 启动时固定的 bootstrap config
2. `agent.settings.get / update` 对应的普通 settings snapshot
3. `agent.task_inspector.config.get / update` 对应的 inspector runtime config
4. 一些运行时逻辑直接现读 `runEngine.Settings()`
5. 一些底层依赖（workspace root / file system / execution / model service）在启动时就已经绑定，不会随着 settings snapshot 自动重建

这导致“前端看到的设置值”“后端返回的设置值”“后端真正运行时使用的配置”可能不是同一套。

#### 1. 巡检配置分裂

桌面端把任务来源目录、工作区路径都改成同一个绝对路径后，便签页可以读取到 markdown 文件，但点击“立即巡检”仍会返回：

`本次巡检解析 0 个文件，识别 0 条事项，逾期 0 条。`

这并不总是“目录里没有事项”，而是后端巡检可能根本没有扫到当前用户以为正在使用的目录。

根因之一是：

- `task_automation.task_sources` 属于 settings snapshot
- `task inspector` 还有一份独立的 `InspectorConfig`
- 手动巡检优先使用 `target_sources`，没有时才回退到 `InspectorConfig`
- 底层 `fileSystem` 又绑定在 bootstrap 时的 `WorkspaceRoot`

也就是说，巡检相关配置不是单一真源。

#### 2. workspace_path 并不等于后端真实工作区根

设置里的 `general.download.workspace_path` 会进入 settings snapshot，也会影响部分展示/摘要逻辑，但不会自动重建已经启动好的 workspace-bound runtime：

- `LocalFileSystemAdapter`
- `executionBackend`
- `execution.Service.workspace`

所以用户在设置里改了工作区路径，不代表后端底层文件系统根真的切过去了。

#### 3. 模型设置和其他设置热更新语义不一致

从 `settings.update` 实现看：

- `models.provider / base_url / model / api_key` 会被标记为 `restart_required`
- `general.language` 变化也会触发 `restart_required`
- 但像 `budget_auto_downgrade` 又会在运行时现读 `runEngine.Settings()`
- 还有一些字段虽然能存进 settings snapshot，但没有看到它们被明确消费成真正运行时行为

这意味着 settings.update 当前不是“统一热更新”，而是：
- 一部分只是快照更新
- 一部分会立刻影响部分逻辑
- 一部分必须重启
- 一部分可能只是被保存/回显，但没有正式运行时语义

#### 4. 错误语义不清晰

以巡检为例，当 source 不可访问、越界、根路径不匹配时，当前逻辑可能静默吞掉遍历错误，最后返回成功的 `0/0/0` 摘要，而不是明确错误。

这会让前端和用户误以为配置已生效，只是目录里没有任务。

---

#### 启动时固定绑定的 runtime

- `services/local-service/internal/config/config.go`
- `services/local-service/cmd/server/main.go`
- `services/local-service/internal/bootstrap/bootstrap.go`

`WorkspaceRoot` 默认来自 `config.Load()`，bootstrap 时构造：

- `LocalFileSystemAdapter`
- `executionBackend`
- `modelService`

这些都不是 settings snapshot 热更新驱动的。

#### 普通 settings snapshot

- `services/local-service/internal/runengine/engine.go`
- `services/local-service/internal/orchestrator/service.go`

`agent.settings.update` 只会更新 `runEngine.settings` 并持久化 snapshot，不会自动重建已启动 runtime 依赖。

#### inspector runtime config

- `services/local-service/internal/runengine/engine.go`
- `services/local-service/internal/orchestrator/service.go`

`InspectorConfig()` / `UpdateInspectorConfig()` 维护的是单独的 `e.inspector`，并不是 `settings.task_automation` 的直接镜像或唯一真源。

#### 巡检执行

- `services/local-service/internal/orchestrator/service.go`
- `services/local-service/internal/taskinspector/service.go`

`TaskInspectorRun` 优先用请求里的 `target_sources`；没有时才回退到 `InspectorConfig`。  
`s.inspectSources()` 当前对遍历失败场景的错误语义也不够清晰。

---

### 影响范围

这个问题不只影响巡检，还影响整个 settings 体系的可预期性，至少包括：

- `general.download.workspace_path`
- `task_automation.task_sources`
- `task_automation.inspect_on_startup`
- `task_automation.inspect_on_file_change`
- `task_automation.inspection_interval`
- `task_automation.remind_before_deadline`
- `task_automation.remind_when_stale`
- `models.provider`
- `models.base_url`
- `models.model`
- `models.api_key`
- `models.credentials.budget_auto_downgrade`
- `general.language`

以及其他已经进入 settings snapshot、但运行时语义不清或未统一声明的字段。

---

### 期望行为

后端需要明确“每个设置项”的正式语义，而不是只提供一个统一的 settings snapshot 外壳。

建议至少做到：

#### 1. 定义单一真源

需要明确：

- 哪些设置由 bootstrap config 驱动
- 哪些设置由 `agent.settings.update` 驱动
- 哪些设置由独立 runtime config 驱动
- 是否允许 `task_inspector.config.*` 与 `settings.task_automation.*` 并存

如果并存，必须定义同步规则；如果不应并存，应收敛成单一正式入口。

#### 2. 为每类设置定义 apply mode

建议把设置分成至少三类：

- hot-reload: 更新后立即影响运行时
- restart-required: 更新后必须重启后端/桌面端
- snapshot-only / ui-only: 仅用于展示、回显或未来能力预留，不直接驱动当前 runtime

并且应当对每个设置项给出明确归属，而不是只在少数字段上零散写 `need_restart=true`。

#### 3. 修正 workspace 相关语义

如果 `workspace_path` 只是展示路径或交付路径，就不应让前端/用户误解成“后端真实工作区根”。

如果它的设计目标本来就是驱动后端真实工作区根，那就需要：

- 明确 `restart_required`
- 或者实现完整的 runtime 重建与切换

#### 4. 修正巡检错误语义

对于 source 不存在、不可访问、超出当前运行时根、路径配置漂移等情况，应返回明确错误，不应再返回成功的 `0/0/0`。

#### 5. 补正式文档

建议同步补一份设置语义文档或协议说明，至少明确：

- 字段归属
- 真源
- 是否热更新
- 是否需要重启
- 当前是否已正式接线到 runtime

---

### 建议验收标准

1. 对当前全部正式 settings 字段给出归类：
   - hot-reload
   - restart-required
   - snapshot-only / ui-only

2. `task_automation` 与 `task_inspector.config` 的关系收敛清楚

3. `workspace_path` 的运行时语义清楚，避免和 bootstrap `WorkspaceRoot` 混淆

4. 巡检对错误目录/漂移目录返回明确错误，而不是成功的 0 摘要

5. 前端不再需要靠推测来决定“这个设置到底有没有真正影响后端运行时”

### PR DESCRIPTION
**Pull request by jinyu918**
## Summary

- unify task inspector config around `settings.task_automation` so compatibility RPCs no longer drift from persisted settings
- fail explicitly when inspection sources are missing, unreadable, or outside the workspace instead of returning a silent `0/0/0` success summary
- mark `general.download.workspace_path` updates as `restart_required` and add regression coverage for task inspector and RPC transport paths

## Problem

Issue #345 points out several inconsistencies in the current settings and task-inspector flow:

- `agent.settings.*` and `agent.task_inspector.config.*` could diverge because they were not using the same effective source of truth
- manual inspection could silently succeed even when source paths were invalid or unreadable
- `workspace_path` looked configurable at runtime even though the bound workspace runtime was not actually rebuilt hot

## What Changed

- changed `agent.task_inspector.config.get / update` to read and write through `settings.task_automation`
- changed `agent.task_inspector.run` to use the settings-backed inspector config when `target_sources` is not provided
- added explicit task-inspector errors for:
  - missing filesystem binding
  - source outside workspace
  - source not found
  - source unreadable
- preserved compatibility for workspace-virtual paths and workspace-local absolute paths
- treated `general.download.workspace_path` as persisted-but-restart-required in both preview and committed update flows
- updated protocol/module docs to reflect the new source-of-truth and restart semantics

## Tests

- `go test ./internal/taskinspector ./internal/orchestrator ./internal/runengine ./internal/rpc -cover`
- `go test ./...`
- `go vet ./internal/taskinspector ./internal/orchestrator ./internal/runengine ./internal/rpc`

## Notes

- this PR intentionally does not implement runtime workspace hot-rebuild
- `workspace_path` is now made explicit as a restart-required setting so behavior matches actual runtime constraints
- compatibility RPCs are preserved, but they now reuse the same settings-backed data path

Fixes #345

### CODE REVIEW

**Comment by jinyu918** [comment]
@xgopilot 还有什么问题

File: services/local-service/internal/taskinspector/service.go [hunk 1]
```diff
@@ -166,25 +200,59 @@ func dedupeNonEmptyStrings(values []string) []string {
 	return result
 }
 
-func sourceToFSPath(source string) string {
+// sourceToFSPath accepts both workspace-virtual paths and legacy absolute paths
+// that still point inside the current workspace root.
+func sourceToFSPath(fileSystem platform.FileSystemAdapter, source string) (string, error) {
```
Comment (MeteorsLiu) [inline services/local-service/internal/taskinspector/service.go:246]: 这个函数看起来是专门为了unix类操作系统写的，你们的windows环境有测试吗，我没看见有

Comment (jinyu918) [reply services/local-service/internal/taskinspector/service.go:246]: 这个问题在这里面已经基本处理了。sourceToFSPath() 对绝对路径分支用的是 filepath.IsAbs / filepath.Clean / fileSystem.Rel，不是纯 Unix 路径逻辑。然后测试的话我本地在 Windows 环境跑的 go test ./services/local-service/internal/taskinspector，也是通过的。

File: services/local-service/internal/taskinspector/service.go [hunk 2]
```diff
@@ -219,25 +241,119 @@ func dedupeNonEmptyStrings(values []string) []string {
...
 	source = strings.TrimSpace(source)
 	if source == "" {
-		return ""
+		return "", nil
+	}
+	normalizedSource := strings.ReplaceAll(source, "\\", "/")
```
Comment (MeteorsLiu) [inline services/local-service/internal/taskinspector/service.go]: 你应该用 `filepath.ToSlash`

Comment (MeteorsLiu) [reply services/local-service/internal/taskinspector/service.go]: 统一 separator：进入函数第一步就 source = filepath.ToSlash(source)，所有后续 path.Clean / 前缀判断都在 forward-slash 语义下工作；越界检查同时能覆盖 ..\。

去掉 nil-fileSystem 绝对路径分支的“返回带盘符绝对路径”行为：要么当作未配置错误，要么按其它分支一致返回相对形式。
（可选）明确 policy：在 Windows 上如何处理 Unix 风格绝对路径（推荐：非 IsAbs 且以 / 开头的输入，视为 legacy 绝对路径显式拒绝或显式走 EnsureWithinWorkspace）。

在 service_test.go 加一组跑在 runtime.GOOS == "windows" 下的用例（或用纯字符串注入的 fake FileSystemAdapter）覆盖：C:\ws\sub\a.md、sub\a.md、workspace/..\evil、..\evil

Comment (jinyu918) [reply services/local-service/internal/taskinspector/service.go]: 已按建议进行修改

**Review by MeteorsLiu — APPROVED** [review]

**Review by Blackcloudss — APPROVED** [review]
